### ISSUE TITLE
BatchNode documentation show invalid chaining methods

### ISSUE THREAD

**Issue by ptrdlbrg** [influxdata/docs.influxdata.com#2008]
###### URL for relevant page?
https://docs.influxdata.com/kapacitor/v1.5/nodes/batch_node/

###### What products and version are you using?
Kapacitor 1.5.1 on Docker (kapacitor:1.5.1-alpine)

###### Where did you look before opening the issue?
Other github issues, such as 1305 and 1602. Google search for better examples. 

###### What is the problem?
The BatchNode documentation indicates that `deadman` and `stats` are valid chaining methods, but they cause panics when used with the `batch` variable. If they are valid chaining methods, the documentation doesn't make clear when one should use those chaining methods on a batch node.

Any attempt to use those chaining methods causes a panic. For example, enabling the TICKscript
```
batch|stats(1m)
```
Causes the following error when watching the logs with the `kapacitor logs` command:
```
ts=2018-11-20T18:34:12.972Z lvl=error msg="2018/11/20 18:34:12 http: panic serving 192.168.112.4:52018: interface conversion: kapacitor.Node is *kapacitor.NoOpNode, not *kapacitor.QueryNode
goroutine 301 [running]:
net/http.(*conn).serve.func1(0xc42001a1e0)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x1da1660, 0xc4203e3780)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/influxdata/kapacitor.(*BatchNode).DBRPs(0xc4203ca240, 0x1, 0x1, 0xc420319c20, 0x22acf00, 0xc4205523d0)
	/root/go/src/github.com/influxdata/kapacitor/batch.go:69 +0x261
github.com/influxdata/kapacitor.(*ExecutingTask).checkDBRPs(0xc4205c62d0, 0xc4203ca240, 0x0, 0x1c4d160)
	/root/go/src/github.com/influxdata/kapacitor/task.go:296 +0x75
github.com/influxdata/kapacitor.(*ExecutingTask).StartBatching(0xc4205c62d0, 0xc4209bb280, 0xc4205c62d0)
	/root/go/src/github.com/influxdata/kapacitor/task.go:259 +0x63
github.com/influxdata/kapacitor/services/task_store.(*Service).startTask(0xc420159e00, 0xc420470438, 0x4, 0x1, 0xc4204b0c80, 0x1, 0x1, 0xc4203833e0, 0x21, 0x0, ...)
	/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:2007 +0x198
github.com/influxdata/kapacitor/services/task_store.(*Service).handleUpdateTask(0xc420159e00, 0x22c6f00, 0xc4204b01e0, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:1044 +0xc86
github.com/influxdata/kapacitor/services/task_store.(*Service).(github.com/influxdata/kapacitor/services/task_store.handleUpdateTask)-fm(0x22c6f00, 0xc4204b01e0, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/task_store/service.go:134 +0x48
github.com/influxdata/kapacitor/services/httpd.authorize.func1(0x22c6f00, 0xc4204b01e0, 0xc420cc8000, 0x2104d7d, 0xa, 0x1, 0x3476f50, 0x0, 0x0, 0xc420430ab0)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:722 +0xe9
github.com/influxdata/kapacitor/services/httpd.authenticate.func1(0x22c6f00, 0xc4204b01e0, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:587 +0xb45
net/http.HandlerFunc.ServeHTTP(0xc4202f5d00, 0x22c6f00, 0xc4204b01e0, 0xc420cc8000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/influxdata/kapacitor/services/httpd.jsonContent.func1(0x22c6f00, 0xc4204b01e0, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:826 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc4202f5d40, 0x22c6f00, 0xc4204b01e0, 0xc420cc8000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/influxdata/kapacitor/services/httpd.gzipFilter.func1(0x22be780, 0xc4204b01c0, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:819 +0x1d5
net/http.HandlerFunc.ServeHTTP(0xc4202f5d60, 0x22be780, 0xc4204b01c0, 0xc420cc8000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/influxdata/kapacitor/services/httpd.versionHeader.func1(0x22be780, 0xc4204b01c0, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:835 +0xbc
net/http.HandlerFunc.ServeHTTP(0xc4202f5d80, 0x22be780, 0xc4204b01c0, 0xc420cc8000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/influxdata/kapacitor/services/httpd.cors.func1(0x22be780, 0xc4204b01c0, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:868 +0x102
net/http.HandlerFunc.ServeHTTP(0xc4202f5da0, 0x22be780, 0xc4204b01c0, 0xc420cc8000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/influxdata/kapacitor/services/httpd.requestID.func1(0x22be780, 0xc4204b01c0, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:878 +0x124
net/http.HandlerFunc.ServeHTTP(0xc4202f5dc0, 0x22be780, 0xc4204b01c0, 0xc420cc8000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/influxdata/kapacitor/services/httpd.logHandler.func1(0x22be780, 0xc4204b0180, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:886 +0xdf
net/http.HandlerFunc.ServeHTTP(0xc42067da40, 0x22be780, 0xc4204b0180, 0xc420cc8000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/influxdata/kapacitor/services/httpd.recovery.func1(0x22c69c0, 0xc420630000, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:895 +0xed
net/http.HandlerFunc.ServeHTTP(0xc42067da70, 0x22c69c0, 0xc420630000, 0xc420cc8000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/influxdata/kapacitor/services/httpd.(*ServeMux).ServeHTTP(0xc4203c3a40, 0x22c69c0, 0xc420630000, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/mux.go:163 +0x130
github.com/influxdata/kapacitor/services/httpd.(*Handler).ServeHTTP(0xc4203bc5a0, 0x22c69c0, 0xc420630000, 0xc420cc8000)
	/root/go/src/github.com/influxdata/kapacitor/services/httpd/handler.go:373 +0xd4
net/http.serverHandler.ServeHTTP(0xc42038e820, 0x22c69c0, 0xc420630000, 0xc420cc8000)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42001a1e0, 0x22c9840, 0xc420186140)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
" service=http service=httpd_server_errors
```

The source code causing the error (batch.go, line 69) seems to indicate that `batch` should always be used with the `query` chaining method. 

I understand that the TICKscript that causes the error doesn't look too useful, but the documentation indicated that it was valid. I tried it to see if I could get a batch to emit a periodic event without the need to query anything. 

A separate, but related, issue with the same documentation page is that the deadman example code also shows `batch` used with the `from()` chaining method. This is clearly incorrect since `batch` doesn't support `from()` as a chaining method. This may be a separate documentation issue, but if the deadman and stats sections get removed then this problem is not relevant.

**Comment by sanderson** [comment]
I've passed the panic on to the Kapacitor team and have updated the documentation so that each batch example includes the `query` chaining method and have called out that every batch node needs a `query` chaining method. A batch cannot be performed without a `query` because it defines the source and scope of the batch.
